// Persistence for the household recipe corpus. localStorage for now; moves to
// data/recipes/*.json once the GitHub data repo is connected.
//
// First run seeds from the bundled cookbook corpus at src/data/cookbookRecipes.json
// (generated by `npm run import:epub`, gitignored to keep copyrighted recipe text
// out of the repo). The glob import tolerates the file being absent — a fresh
// clone before running the importer just starts with an empty book.
import { storage, StorageKeys } from "./storage";
import { emptyRecipeBook, normalizeRecipeBook, type RecipeBook } from "../domain/recipes";

const bundled = import.meta.glob("../data/cookbookRecipes.json", { eager: true });

function seedBook(): RecipeBook {
  const mod = Object.values(bundled)[0] as { default?: unknown } | undefined;
  return mod?.default ? normalizeRecipeBook(mod.default) : emptyRecipeBook();
}

export function loadRecipes(): RecipeBook {
  try {
    const raw = storage.get(StorageKeys.recipes);
    if (raw) return normalizeRecipeBook(JSON.parse(raw));
  } catch {
    // fall through to the bundled seed
  }
  return seedBook();
}

export function saveRecipes(book: RecipeBook): void {
  storage.set(StorageKeys.recipes, JSON.stringify(book));
}
